data:
    dataset: "HAM10000"
    seed: 2000
    label_min_max: [0.001, 0.999]
    num_classes: 7
    num_workers: 4
    data_dir: '/kaggle/input/datasets/surajghuwalewala/ham1000-segmentation-and-classification/images'
    traindata: '/kaggle/input/datasets/surajghuwalewala/ham1000-segmentation-and-classification/GroundTruth.csv'
    testdata: '/kaggle/input/datasets/surajghuwalewala/ham1000-segmentation-and-classification/GroundTruth.csv'

model:
    type: "simple"
    data_dim: 150528
    n_input_channels: 3
    n_input_padding: 0
    feature_dim: 6144
    hidden_dim: 6144
    cat_x: True
    cat_y_pred: True
    arch: resnet18
    var_type: fixedlarge
    ema_rate: 0.9999
    ema: True
    num_k: 6

flow_matching:
    num_steps: 10
    interp: straight

aux_cls:
    n_pretrain_epochs: 20
    logging_interval: 1

training:
    batch_size: 32
    lr: 1e-4
    weight_decay: 1e-4
    mixed_precision: true
    scheduler: cosine
    n_epochs: 50
    warmup_epochs: 5
    add_t0_loss: False
    n_steps_req_grad: 100
    n_minibatches_add_ce: 20
    n_ce_epochs_warmup: 10
    n_ce_epochs_interval: 50
    n_sanity_check_epochs_freq: 500
    snapshot_freq: 1000000000
    logging_freq: 100
    validation_freq: 5
    image_folder: 'training_image_samples'

sampling:
    batch_size: 8
    sampling_size: 1000
    last_only: True
    image_folder: 'sampling_image_samples'

testing:
    batch_size: 8
    sampling_size: 1000
    last_only: True
    plot_freq: 200
    image_folder: 'testing_image_samples'
    n_samples: 100
    n_bins: 10
    compute_metric_all_steps: False
    metrics_t: 0
    ttest_alpha: 0.05
    trimmed_mean_range: [0.0, 100.0]
    PICP_range: [2.5, 97.5]
    make_plot: True
    squared_plot: True
    plot_true: True
    plot_gen: True
    fig_size: [8, 5]

optim:
    weight_decay: 1e-4
    optimizer: "Adam"
    lr: 1e-4
    beta1: 0.9
    amsgrad: False
    eps: 0.00000001
    grad_clip: 1.0
    lr_schedule: True
    min_lr: 0.0

aux_optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.001
    beta1: 0.9
    amsgrad: True
    eps: 0.00000001
    grad_clip: 1.0
